"""initial

Revision ID: 3b491ceedb36
Revises: 
Create Date: 2026-08-15 12:48:53.601711

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3b491ceedb36'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('models',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('params_b', sa.Float(), nullable=True),
    sa.Column('vram_required_mb', sa.Integer(), nullable=False),
    sa.Column('requires_hf_token', sa.Boolean(), nullable=False),
    sa.Column('license', sa.String(length=64), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('workers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('os', sa.String(length=64), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('memory_mb', sa.Integer(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_cluster_id'), 'workers', ['cluster_id'], unique=False)
    op.create_table('model_instances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=True),
    sa.Column('engine', sa.String(length=16), nullable=False),
    sa.Column('profile', sa.String(length=16), nullable=False),
    sa.Column('gpu_indexes', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_instances_cluster_id'), 'model_instances', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_model_instances_model_id'), 'model_instances', ['model_id'], unique=False)
    op.create_index(op.f('ix_model_instances_worker_id'), 'model_instances', ['worker_id'], unique=False)
    op.create_table('worker_gpus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('vram_mb', sa.Integer(), nullable=False),
    sa.Column('used_vram_mb', sa.Integer(), nullable=False),
    sa.Column('utilization_pct', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=128), nullable=True),
    sa.Column('driver_version', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_gpus_worker_id'), 'worker_gpus', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_gpus_worker_id'), table_name='worker_gpus')
    op.drop_table('worker_gpus')
    op.drop_index(op.f('ix_model_instances_worker_id'), table_name='model_instances')
    op.drop_index(op.f('ix_model_instances_model_id'), table_name='model_instances')
    op.drop_index(op.f('ix_model_instances_cluster_id'), table_name='model_instances')
    op.drop_table('model_instances')
    op.drop_index(op.f('ix_workers_cluster_id'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('models')
    op.drop_table('clusters')
    # ### end Alembic commands ###
